// examples/astro/src/components/solid/solid-card.tsx
import { createSignal } from "solid-js";

interface SolidCardProps {
  title: string;
}

export default (props: SolidCardProps) => {
  const [count, setCount] = createSignal(0);
  return (
    <div data-testid="solid-card" style={{ border: "1px solid #e0e0e0", "border-radius": "12px", padding: "16px", background: "#fafafa" }}>
      <h3 style={{ "font-size": "16px", "margin-bottom": "8px" }}>{props.title} (Solid)</h3>
      <p style={{ color: "#444", "margin-bottom": "12px", "font-size": "14px" }}>Count: {count()}</p>
      <button
        onclick={() => setCount((previous) => previous + 1)}
        style={{ padding: "8px 16px", border: "none", "border-radius": "8px", background: "#2ecc71", color: "white", "font-size": "14px", cursor: "pointer" }}
      >
        Increment
      </button>
    </div>
  );
};

// examples/astro/src/components/svelte-card.svelte
<script>
  let count = $state(0);
  let { title } = $props();
</script>

<div data-testid="svelte-card" style="border: 1px solid #e0e0e0; border-radius: 12px; padding: 16px; background: #fafafa;">
  <h3 style="font-size: 16px; margin-bottom: 8px;">{title} (Svelte)</h3>
  <p style="color: #444; margin-bottom: 12px; font-size: 14px;">Count: {count}</p>
  <button onclick={() => count++} style="padding: 8px 16px; border: none; border-radius: 8px; background: #e55039; color: white; font-size: 14px; cursor: pointer;">
    Increment
  </button>
</div>
