// examples/vite-solid/src/app.tsx
import { SampleCard } from "./sample-card";
import { InspectorOverlay } from "./inspector-overlay";

export const App = () => (
  <div
    style={{ "font-family": "system-ui", padding: "24px", "max-width": "480px", margin: "0 auto" }}
  >
    <h1 style={{ "font-size": "20px", "margin-bottom": "4px" }}>Element Source - Vite + Solid</h1>
    <div style={{ display: "flex", "flex-direction": "column", gap: "12px" }}>
      <SampleCard title="Counter" />
      <SampleCard title="Timer" />
      <SampleCard title="Toggle" />
    </div>
    <InspectorOverlay />
  </div>
);

// examples/vite-svelte/src/App.svelte
<script lang="ts">
  import SampleCard from "./sample-card.svelte";
  import InspectorOverlay from "./inspector-overlay.svelte";
</script>

<div class="app">
  <h1>Element Source - Vite + Svelte</h1>

  <div class="card-grid">
    <SampleCard title="Counter" />
    <SampleCard title="Timer" />
    <SampleCard title="Toggle" />
  </div>

  <InspectorOverlay />
</div>

<style>
  :global(*) {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  .app {
    font-family: system-ui, -apple-system, sans-serif;
    padding: 24px;
    max-width: 480px;
    margin: 0 auto;
  }

  h1 {
    font-size: 20px;
    margin-bottom: 24px;
  }

  .card-grid {
    display: flex;
    flex-direction: column;
    gap: 12px;
  }
</style>
